// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOwXqEaApGZjlz9DOdXZ1B4gotJdKZzEg',
    appId: '1:744426332508:web:000c544455d56e826ca199',
    messagingSenderId: '744426332508',
    projectId: 'rukmal-fish-delivery-4fb4f',
    authDomain: 'rukmal-fish-delivery-4fb4f.firebaseapp.com',
    storageBucket: 'rukmal-fish-delivery-4fb4f.firebasestorage.app',
    measurementId: 'G-4H2QL2FLFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCEPezCXFW2xzNZdL38jWvyuJWEdwmO-c',
    appId: '1:744426332508:android:ec15eef162224b356ca199',
    messagingSenderId: '744426332508',
    projectId: 'rukmal-fish-delivery-4fb4f',
    storageBucket: 'rukmal-fish-delivery-4fb4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvj_RTPxiZCmxWzaFWUVgkTXznkKMUh5A',
    appId: '1:744426332508:ios:d097ae4a3e36f1b66ca199',
    messagingSenderId: '744426332508',
    projectId: 'rukmal-fish-delivery-4fb4f',
    storageBucket: 'rukmal-fish-delivery-4fb4f.firebasestorage.app',
    iosBundleId: 'com.example.netproft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvj_RTPxiZCmxWzaFWUVgkTXznkKMUh5A',
    appId: '1:744426332508:ios:d097ae4a3e36f1b66ca199',
    messagingSenderId: '744426332508',
    projectId: 'rukmal-fish-delivery-4fb4f',
    storageBucket: 'rukmal-fish-delivery-4fb4f.firebasestorage.app',
    iosBundleId: 'com.example.netproft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOwXqEaApGZjlz9DOdXZ1B4gotJdKZzEg',
    appId: '1:744426332508:web:4f4d122bc077c0626ca199',
    messagingSenderId: '744426332508',
    projectId: 'rukmal-fish-delivery-4fb4f',
    authDomain: 'rukmal-fish-delivery-4fb4f.firebaseapp.com',
    storageBucket: 'rukmal-fish-delivery-4fb4f.firebasestorage.app',
    measurementId: 'G-2W45YJBC1E',
  );
}
